version: "3.7"
services:
  mongodb_empresa:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=dbexample
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - "./mongo-volume:/data/db"
    ports:
      - "27017:27017"
    restart: always
      
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    container_name: activemq
    environment:
      - "TZ=America/Santiago"
    volumes:
      - "./activemq-volume/lib:/opt/activemq/lib"
      - "./activemq-volume/conf:/opt/activemq/conf"
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://IP_LOCAL:8161/admin (admin:admin)
    restart: always
  
  dbtoactivemq:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: activemq_db
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" # http://IP_LOCAL:5050 (admin@admin.com:root)